language: php

php:
    - 7.2
    - 7.3
    - 7.4

branches:
    only:
        - master

install:
    - composer install

script:
    - composer test

notifications:
    email: false

after_success:
    - cd build/logs && bash <(curl -s https://codecov.io/bash)
